baseURL = 'https://learyliang.com/'
languageCode = 'en-us'
title = '戯言手帳'
theme = "github-style"

[params]
  author = "Leary Liang"
  description = "Leary Liang 的戯言手帳。"
  github = "LearyN"
  avatar = "https://pbs.twimg.com/profile_images/1907332842373427200/tdOsvRjM_400x400.jpg"
favicon = "https://www.google.com/favicon.ico"
