name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  # 允许手动触发
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/3bedc9f6-9717-4f8d-8568-630aa9734f3a"